services:
  - type: web
    name: users-management-api
    runtime: docker
    plan: free
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /v3/api-docs
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: crud_usuarios
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_ADDRESS
        sync: false
      - key: SMTP_FROM_NAME
        value: Gestion de Usuarios
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_SECONDS
        value: "900"
